** Disclaimer
  I am writing this code to get familiar with c.  My goal is
  to pimp this up a little, so that it might actually be possible to print
  sudokus in a nice way and waste some time solving them by hand.

** TODO Things that need to be done in my code: [1/4]
   - [X] Rewrite commit history.
     + I did this with the following command:
       git filter-branch --commit-filter 'export GIT_AUTHOR_EMAIL="mail"; export GIT_AUTHOR_NAME="First Last"; export GIT_COMMITTER_NAME="First Last"; GIT_COMMITTER_EMAIL="email"; git commit-tree "$@"'
     + Check results with git log --pretty=fuller
   - [ ] Free the mallocs of reader.c
   - [ ] Add option to interactive mode, so that ps can be printed at the given state.
   - [ ] Implement golden chains
 
** Copyright
*** Thoughts
    The Apache2 license seems reasonable.  I really do not care what anyone
    does with my code, as long as I do not take any damage of it.  So
    take the code if you want, and have fun with it.  (Or not, whatever...)
*** The License
    Copyright 2013 Superidiot

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

       	http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
